### ISSUE TITLE
分享到QQ时选择联系人后弹出的对话框的封面不正确

### ISSUE THREAD

**Issue by merbng** [tsy12321/SocialSDKAndroid#10]
![Uploading QQ截图20170408113954.png…]()

**Comment by tsy12321** [comment]
图看不到。

**Comment by merbng** [comment]
由于上传图片总是失败，就在这里问题描述：
分享到QQ时， 弹出选择好友--点击某好友--弹出的预览框，预览框的封面图一直是第一次分享的那个图，

QQHandler这个类的104行，获取根路径，我将图片命名为随机名称 才修复，但是这样每次分享都会在手机创建一张图。。
