### ISSUE TITLE
微博SDK更新调整

### ISSUE THREAD

**Issue by merbng** [tsy12321/SocialSDKAndroid#11]
微博SDK 3.2中微博分享进行了大调整https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E6%96%B0%E6%96%87%E6%A1%A3/%E5%BE%AE%E5%8D%9ASDK%203.2%E6%96%87%E6%A1%A3.pdf

**Comment by tsy12321** [comment]
👍  我来看下更新下

**Comment by tsy12321** [comment]
已经更新了。v1.7.0
