### ISSUE TITLE
微信登录没有返回信息？

### ISSUE THREAD

**Issue by walter201230** [tsy12321/SocialSDKAndroid#15]
可以进行微信分享，微信登录也可以弹出页面，按授权后，没有接受到相应的返回信息。

**Comment by walter201230** [comment]
![image](https://cloud.githubusercontent.com/assets/12378130/25890477/2bae216e-35a0-11e7-81f8-24a0e654647a.png)

**Comment by tsy12321** [comment]
已更新 最新微信sdk
