### ISSUE TITLE
QQ登录可以回调成功，微博不成功，点击后直接关闭当前界面了

### ISSUE THREAD

**Issue by sendtion** [tsy12321/SocialSDKAndroid#2]
QQ登录可以回调成功，可以看到打印的成功信息。
微信可以到点击登录那里，然后点击后看不到回调接口的打印信息，说明没成功！
微博点击调用按钮，直接闪退到上一界面，关闭了当前界面。

**Comment by tsy12321** [comment]
微信检查有没有加WXEntryActivity
微博也是检查AndroidManifest有没有加相应配置
