### ISSUE TITLE
请问一下，导入你的jar包运行报这个错误

### ISSUE THREAD

**Issue by lmz1993** [tsy12321/SocialSDKAndroid#4]
Error:Execution failed for task ':buddhidmapp:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/tencent/mm/sdk/a/a$a.class

**Comment by tsy12321** [comment]
你的腾讯的包导入了2次。是不是你以前项目里已经有了腾讯的包

**Comment by lmz1993** [comment]
恩，用了你的支付的库，在用你的登录的库后造成的，你的这两个库不能同时使用怎么破呢？

**Comment by tsy12321** [comment]
登录的库不需要将tecent的jar包放进去。支付库正常使用就ok拉

**Comment by lmz1993** [comment]
您好，还不是不行啊！！！无法拉取微信授权页，方便加一下QQ吗？我的（281549017）

**Comment by tsy12321** [comment]
你加微信tsy12321吧
