### ISSUE TITLE
QQ登录没有回调

### ISSUE THREAD

**Issue by Wingge** [tsy12321/SocialSDKAndroid#5]
QQ登录没有回调，但是提示已授权，
![os owu b ol dv 9r](https://cloud.githubusercontent.com/assets/3727884/21880538/7f95313c-d8da-11e6-8337-6ad4c5d0b3d3.png)

但是有结果打印
![image](https://cloud.githubusercontent.com/assets/3727884/21880564/a1c4cff6-d8da-11e6-93df-4e5d4c82a49f.png)

**Comment by Wingge** [comment]
哦，是不是因为我在fragment无法接收返回？

**Comment by Wingge** [comment]
希望您能看到，帮我看一下

**Comment by Wingge** [comment]
解决了~是fragment回调问题，

**Comment by tsy12321** [comment]
。。。。
