### ISSUE TITLE
同一个ShareVideoMedia，微博分享出来图片显示正常，微信则显示不出来图片

### ISSUE THREAD

**Issue by woniu0936** [tsy12321/SocialSDKAndroid#6]
还有一个问题，打开activity，新浪微博分享，随机出现第 1~3次（连续）分享没反应，但是打开activity先分享朋友圈，再分享新浪微博就没问任何问题。而且经过测试发现，打开activity，第一次点击分享，在doShare方法哪里打一个断点，然后点击新浪微博分享，走到断点处，让断点走完，则能分享成功（成功率百分之百）

**Comment by woniu0936** [comment]
是我的问题，图片加载是异步的，图片还没加载完，就发送分享请求了。如果可以，希望你能加入对图片ImageUrl的支持

**Comment by tsy12321** [comment]
好的 感谢反馈
