### ISSUE TITLE
app中多个activity有分享操作时，新浪微博的问题

### ISSUE THREAD

**Issue by woniu0936** [tsy12321/SocialSDKAndroid#7]
我在app中有多个activity提供分享功能，这时候在manifest中对应的每个activity中添加
          `
            <intent-filter>
                <action android:name="com.sina.weibo.sdk.action.ACTION_SDK_REQ_ACTIVITY" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>`
这时候新浪微博的分享回调会弹出一个dialog，里面有多个选项供选择，这些选项都是本app

**Comment by woniu0936** [comment]
是不是应该和友盟分享一样，写个activity专门接收
`<intent-filter> 
          <action android:name="com.sina.weibo.sdk.action.ACTION_SDK_REQ_ACTIVITY" /> 
          <category android:name="android.intent.category.DEFAULT" /> 
</intent-filter>`
然后在此activity种做微博回调的分发，将微博的回调信息发送给对应的分享页面？

**Comment by tsy12321** [comment]
感谢反馈、我看下啊

**Comment by tsy12321** [comment]
v1.6.0更新
抽出了新浪微博的分享回调方法。详细见README啊
